package com.obdiitools.obd

object DTCDatabase {

    private val descriptions = mapOf(
        "P0001" to "Fuel Volume Regulator Control Circuit Open",
        "P0002" to "Fuel Volume Regulator Control Circuit Range/Performance",
        "P0010" to "Intake Camshaft Position Actuator Circuit (Bank 1)",
        "P0011" to "Intake Camshaft Position Timing Over-Advanced or System Performance (Bank 1)",
        "P0012" to "Intake Camshaft Position Timing Over-Retarded (Bank 1)",
        "P0016" to "Crankshaft/Camshaft Position Sensor - Incorrect Correlation (Bank 1)",
        "P0030" to "HO2S Heater Control Circuit (Bank 1, Sensor 1)",
        "P0031" to "HO2S Heater Circuit Low Voltage (Bank 1, Sensor 1)",
        "P0032" to "HO2S Heater Circuit High Voltage (Bank 1, Sensor 1)",
        "P0036" to "HO2S Heater Control Circuit (Bank 1, Sensor 2)",
        "P0037" to "HO2S Heater Circuit Low Voltage (Bank 1, Sensor 2)",
        "P0038" to "HO2S Heater Circuit High Voltage (Bank 1, Sensor 2)",
        "P0068" to "MAP/MAF Sensor - Throttle Position Correlation",
        "P0069" to "MAP Sensor Correlation with Barometric Pressure",
        "P0087" to "Fuel Rail Pressure Too Low",
        "P0088" to "Fuel Rail Pressure Too High",
        "P0089" to "Fuel Pressure Regulator Performance",
        "P0097" to "Intake Air Temperature Sensor 2 Circuit Low Input",
        "P0098" to "Intake Air Temperature Sensor 2 Circuit High Input",
        "P0100" to "Mass Air Flow Sensor Circuit Malfunction",
        "P0101" to "Mass Air Flow Sensor Range/Performance",
        "P0102" to "Mass Air Flow Sensor Low Input",
        "P0103" to "Mass Air Flow Sensor High Input",
        "P0107" to "Manifold Absolute Pressure Sensor Low Input",
        "P0108" to "Manifold Absolute Pressure Sensor High Input",
        "P0110" to "Intake Air Temperature Sensor Circuit Malfunction",
        "P0111" to "Intake Air Temperature Sensor Range/Performance",
        "P0112" to "Intake Air Temperature Sensor Low Input",
        "P0113" to "Intake Air Temperature Sensor High Input",
        "P0116" to "Engine Coolant Temperature Sensor Range/Performance",
        "P0117" to "Engine Coolant Temperature Sensor Low Input",
        "P0118" to "Engine Coolant Temperature Sensor High Input",
        "P0120" to "Throttle Position Sensor Circuit Malfunction",
        "P0121" to "Throttle Position Sensor Range/Performance",
        "P0122" to "Throttle Position Sensor Low Input",
        "P0123" to "Throttle Position Sensor High Input",
        "P0128" to "Coolant Thermostat Below Regulating Temperature",
        "P0131" to "O2 Sensor Low Voltage (Bank 1, Sensor 1)",
        "P0132" to "O2 Sensor High Voltage (Bank 1, Sensor 1)",
        "P0133" to "O2 Sensor Slow Response (Bank 1, Sensor 1)",
        "P0134" to "O2 Sensor No Activity (Bank 1, Sensor 1)",
        "P0135" to "O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)",
        "P0141" to "O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 2)",
        "P0171" to "System Too Lean (Bank 1)",
        "P0172" to "System Too Rich (Bank 1)",
        "P0174" to "System Too Lean (Bank 2)",
        "P0175" to "System Too Rich (Bank 2)",
        "P0191" to "Fuel Rail Pressure Sensor Range/Performance",
        "P0192" to "Fuel Rail Pressure Sensor Low Input",
        "P0193" to "Fuel Rail Pressure Sensor High Input",
        "P0201" to "Injector Circuit Malfunction - Cylinder 1",
        "P0202" to "Injector Circuit Malfunction - Cylinder 2",
        "P0203" to "Injector Circuit Malfunction - Cylinder 3",
        "P0204" to "Injector Circuit Malfunction - Cylinder 4",
        "P0205" to "Injector Circuit Malfunction - Cylinder 5",
        "P0206" to "Injector Circuit Malfunction - Cylinder 6",
        "P0217" to "Engine Coolant Over Temperature Condition",
        "P0219" to "Engine Over Speed Condition",
        "P0230" to "Fuel Pump Primary Circuit Malfunction",
        "P0261" to "Cylinder 1 Injector Circuit Low",
        "P0262" to "Cylinder 1 Injector Circuit High",
        "P0263" to "Cylinder 1 Contribution/Balance Fault",
        "P0300" to "Random/Multiple Cylinder Misfire Detected",
        "P0301" to "Cylinder 1 Misfire Detected",
        "P0302" to "Cylinder 2 Misfire Detected",
        "P0303" to "Cylinder 3 Misfire Detected",
        "P0304" to "Cylinder 4 Misfire Detected",
        "P0305" to "Cylinder 5 Misfire Detected",
        "P0306" to "Cylinder 6 Misfire Detected",
        "P0307" to "Cylinder 7 Misfire Detected",
        "P0308" to "Cylinder 8 Misfire Detected",
        "P0316" to "Misfire Detected on Startup (First 1000 Revolutions)",
        "P0320" to "Ignition/Distributor Engine Speed Input Circuit Malfunction",
        "P0325" to "Knock Sensor Circuit Malfunction (Bank 1)",
        "P0326" to "Knock Sensor Circuit Range/Performance (Bank 1)",
        "P0327" to "Knock Sensor Circuit Low Input (Bank 1)",
        "P0328" to "Knock Sensor Circuit High Input (Bank 1)",
        "P0335" to "Crankshaft Position Sensor Circuit Malfunction",
        "P0336" to "Crankshaft Position Sensor Circuit Range/Performance",
        "P0340" to "Camshaft Position Sensor Circuit Malfunction (Bank 1)",
        "P0341" to "Camshaft Position Sensor Range/Performance (Bank 1)",
        "P0351" to "Ignition Coil A Primary/Secondary Circuit Malfunction",
        "P0352" to "Ignition Coil B Primary/Secondary Circuit Malfunction",
        "P0353" to "Ignition Coil C Primary/Secondary Circuit Malfunction",
        "P0354" to "Ignition Coil D Primary/Secondary Circuit Malfunction",
        "P0400" to "Exhaust Gas Recirculation Flow Malfunction",
        "P0401" to "Exhaust Gas Recirculation Flow Insufficient",
        "P0402" to "Exhaust Gas Recirculation Flow Excessive",
        "P0404" to "Exhaust Gas Recirculation Circuit Range/Performance",
        "P0420" to "Catalyst System Efficiency Below Threshold (Bank 1)",
        "P0421" to "Warm Up Catalyst Efficiency Below Threshold (Bank 1)",
        "P0430" to "Catalyst System Efficiency Below Threshold (Bank 2)",
        "P0440" to "Evaporative Emission Control System Malfunction",
        "P0441" to "Evaporative Emission Control System Incorrect Purge Flow",
        "P0442" to "Evaporative Emission Control System Leak Detected (small leak)",
        "P0446" to "Evaporative Emission Control System Vent Control Circuit Malfunction",
        "P0449" to "Evaporative Emission System Vent Valve/Solenoid Circuit Malfunction",
        "P0451" to "Evaporative Emission Control System Pressure Sensor Range/Performance",
        "P0452" to "Evaporative Emission Control System Pressure Sensor Low Input",
        "P0453" to "Evaporative Emission Control System Pressure Sensor High Input",
        "P0455" to "Evaporative Emission Control System Leak Detected (large leak)",
        "P0456" to "Evaporative Emission Control System Leak Detected (very small leak)",
        "P0460" to "Fuel Level Sensor Circuit Malfunction",
        "P0461" to "Fuel Level Sensor Circuit Range/Performance",
        "P0462" to "Fuel Level Sensor Circuit Low Input",
        "P0463" to "Fuel Level Sensor Circuit High Input",
        "P0480" to "Fan 1 Control Circuit Malfunction",
        "P0481" to "Fan 2 Control Circuit Malfunction",
        "P0500" to "Vehicle Speed Sensor Malfunction",
        "P0501" to "Vehicle Speed Sensor Range/Performance",
        "P0505" to "Idle Control System Malfunction",
        "P0506" to "Idle Control System RPM Lower Than Expected",
        "P0507" to "Idle Control System RPM Higher Than Expected",
        "P0513" to "Incorrect Immobilizer Key",
        "P0560" to "System Voltage Malfunction",
        "P0562" to "System Voltage Low",
        "P0563" to "System Voltage High",
        "P0571" to "Cruise Control/Brake Switch A Circuit Malfunction",
        "P0600" to "Serial Communication Link Malfunction",
        "P0601" to "Internal Control Module Memory Check Sum Error",
        "P0602" to "Control Module Programming Error",
        "P0603" to "Internal Control Module Keep Alive Memory Error",
        "P0604" to "Internal Control Module Random Access Memory Error",
        "P0605" to "Internal Control Module Read Only Memory Error",
        "P0606" to "PCM Processor Fault",
        "P0620" to "Generator Control Circuit Malfunction",
        "P0700" to "Transmission Control System Malfunction",
        "P0705" to "Transmission Range Sensor Circuit Malfunction",
        "P0706" to "Transmission Range Sensor Circuit Range/Performance",
        "P0715" to "Input/Turbine Speed Sensor Circuit Malfunction",
        "P0720" to "Output Speed Sensor Circuit Malfunction",
        "P0730" to "Incorrect Gear Ratio",
        "P0740" to "Torque Converter Clutch Circuit Malfunction",
        "P0741" to "Torque Converter Clutch Circuit Performance or Stuck Off",
        "P0748" to "Pressure Control Solenoid Electrical",
        "P0750" to "Shift Solenoid A Malfunction",
        "P0755" to "Shift Solenoid B Malfunction",
        "P0760" to "Shift Solenoid C Malfunction",
        "P0765" to "Shift Solenoid D Malfunction",
        "P0770" to "Shift Solenoid E Malfunction",
        "U0001" to "High Speed CAN Communication Bus",
        "U0100" to "Lost Communication With ECM/PCM",
        "U0101" to "Lost Communication With TCM",
        "U0121" to "Lost Communication With ABS Control Module",
        "U0155" to "Lost Communication With Instrument Panel Cluster (IPC) Control Module",
        "B0001" to "Driver Frontal Stage 1 Deployment Control",
        "B0010" to "Passenger Frontal Stage 1 Deployment Control",
        "C0031" to "Right Front Wheel Speed Sensor Circuit",
        "C0034" to "Right Front Wheel Speed Sensor Circuit Range/Performance",
        "C0035" to "Left Front Wheel Speed Sensor Circuit",
        "C0040" to "Right Rear Wheel Speed Sensor Circuit",
        "C0045" to "Left Rear Wheel Speed Sensor Circuit",
    )

    fun getDescription(code: String): String =
        descriptions[code.uppercase()] ?: "Unknown fault code"

    fun getSeverity(code: String): Severity {
        return when {
            code.startsWith("P030") -> Severity.HIGH       // Misfires
            code.startsWith("P0420") || code.startsWith("P0430") -> Severity.MEDIUM // Catalyst
            code.startsWith("P0171") || code.startsWith("P0172") -> Severity.MEDIUM // Fuel trim
            code.startsWith("U") -> Severity.HIGH          // Network comm loss
            code.startsWith("B") -> Severity.MEDIUM
            code.startsWith("C") -> Severity.HIGH          // Chassis/ABS
            else -> Severity.LOW
        }
    }

    enum class Severity { LOW, MEDIUM, HIGH }
}
